/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dhyan' at '11/12/16 11:14 AM' with Gradle 2.11
 *
 * @author dhyan, @date 11/12/16 11:14 AM
 */
public class Library {
    public static  void main(String[] args) {
        System.out.println("This is printed from Demo java application");
    }
}
